#include "dc_motor.h"


//电机驱动初始化
void dc_motor_init(void)
{
	GPIO_InitTypeDef GPIO_InitStructure;
	
	RCC_APB2PeriphClockCmd(MOTOR1_IN1_PORT_RCC,ENABLE);
	RCC_APB2PeriphClockCmd(MOTOR1_IN2_PORT_RCC,ENABLE);
	RCC_APB2PeriphClockCmd(MOTOR1_ENA_PORT_RCC,ENABLE);
	RCC_APB2PeriphClockCmd(MOTOR2_IN1_PORT_RCC,ENABLE);
	RCC_APB2PeriphClockCmd(MOTOR2_IN2_PORT_RCC,ENABLE);
	RCC_APB2PeriphClockCmd(MOTOR2_ENA_PORT_RCC,ENABLE);
	RCC_APB2PeriphClockCmd(MOTOR3_IN1_PORT_RCC,ENABLE);
	RCC_APB2PeriphClockCmd(MOTOR3_IN2_PORT_RCC,ENABLE);
	RCC_APB2PeriphClockCmd(MOTOR3_ENA_PORT_RCC,ENABLE);
	RCC_APB2PeriphClockCmd(MOTOR4_IN1_PORT_RCC,ENABLE);
	RCC_APB2PeriphClockCmd(MOTOR4_IN2_PORT_RCC,ENABLE);
	RCC_APB2PeriphClockCmd(MOTOR4_ENA_PORT_RCC,ENABLE);
	//MOTOR1
	GPIO_InitStructure.GPIO_Pin=MOTOR1_IN1_PIN;  
	GPIO_InitStructure.GPIO_Mode=GPIO_Mode_Out_PP;	 
	GPIO_InitStructure.GPIO_Speed=GPIO_Speed_50MHz;	
	GPIO_Init(MOTOR1_IN1_PORT,&GPIO_InitStructure);

	GPIO_InitStructure.GPIO_Pin=MOTOR1_IN2_PIN;  
	GPIO_Init(MOTOR1_IN2_PORT,&GPIO_InitStructure);
	
	GPIO_InitStructure.GPIO_Pin=MOTOR1_ENA_PIN;  
	GPIO_Init(MOTOR1_ENA_PORT,&GPIO_InitStructure);
	
	//MOTOR2
	GPIO_InitStructure.GPIO_Pin=MOTOR2_IN1_PIN;  
	GPIO_Init(MOTOR2_IN1_PORT,&GPIO_InitStructure);

	GPIO_InitStructure.GPIO_Pin=MOTOR2_IN2_PIN;  
	GPIO_Init(MOTOR2_IN2_PORT,&GPIO_InitStructure);
	
	GPIO_InitStructure.GPIO_Pin=MOTOR2_ENA_PIN;  
	GPIO_Init(MOTOR2_ENA_PORT,&GPIO_InitStructure);
	
	//MOTOR3
	GPIO_InitStructure.GPIO_Pin=MOTOR3_IN1_PIN;  
	GPIO_Init(MOTOR3_IN1_PORT,&GPIO_InitStructure);

	GPIO_InitStructure.GPIO_Pin=MOTOR3_IN2_PIN;  
	GPIO_Init(MOTOR3_IN2_PORT,&GPIO_InitStructure);
	
	GPIO_InitStructure.GPIO_Pin=MOTOR3_ENA_PIN;  
	GPIO_Init(MOTOR3_ENA_PORT,&GPIO_InitStructure);
	
	//MOTOR4
	GPIO_InitStructure.GPIO_Pin=MOTOR4_IN1_PIN;  
	GPIO_Init(MOTOR4_IN1_PORT,&GPIO_InitStructure);

	GPIO_InitStructure.GPIO_Pin=MOTOR4_IN2_PIN;  
	GPIO_Init(MOTOR4_IN2_PORT,&GPIO_InitStructure);
	
	GPIO_InitStructure.GPIO_Pin=MOTOR4_ENA_PIN;  
	GPIO_Init(MOTOR4_ENA_PORT,&GPIO_InitStructure);
	
	MOTOR1_IN1=0;MOTOR1_IN2=0;
	MOTOR2_IN1=0;MOTOR2_IN2=0;
	MOTOR3_IN1=0;MOTOR3_IN2=0;
	MOTOR4_IN1=0;MOTOR4_IN2=0;
	MOTOR1_ENA=1;MOTOR2_ENA=1;
	MOTOR3_ENA=1;MOTOR4_ENA=1;
}

//前进
void car_forward(void)
{
	MOTOR1_IN1=0;MOTOR1_IN2=1;
	MOTOR2_IN1=0;MOTOR2_IN2=1;
	
	MOTOR3_IN1=0;MOTOR3_IN2=1;
	MOTOR4_IN1=0;MOTOR4_IN2=1;
}
//后退
void car_back(void)
{
	MOTOR1_IN1=1;MOTOR1_IN2=0;
	MOTOR2_IN1=1;MOTOR2_IN2=0;
	
	MOTOR3_IN1=1;MOTOR3_IN2=0;
	MOTOR4_IN1=1;MOTOR4_IN2=0;
}
//左转
void car_left(void)
{
	MOTOR1_IN1=0;MOTOR1_IN2=0;
	MOTOR2_IN1=0;MOTOR2_IN2=0;
	
	MOTOR3_IN1=0;MOTOR3_IN2=1;
	MOTOR4_IN1=0;MOTOR4_IN2=1;
}
//右转
void car_right(void)
{
	MOTOR1_IN1=0;MOTOR1_IN2=1;
	MOTOR2_IN1=0;MOTOR2_IN2=1;
	
	MOTOR3_IN1=0;MOTOR3_IN2=0;
	MOTOR4_IN1=0;MOTOR4_IN2=0;
}
//停止
void car_stop(void)
{
	MOTOR1_IN1=0;MOTOR1_IN2=0;
	MOTOR2_IN1=0;MOTOR2_IN2=0;
	
	MOTOR3_IN1=0;MOTOR3_IN2=0;
	MOTOR4_IN1=0;MOTOR4_IN2=0;
}

void car_space_high()
{
	MOTOR1_ENA=1;MOTOR2_ENA=1;
	MOTOR3_ENA=1;MOTOR4_ENA=1;
}

void car_space_low()
{
	MOTOR1_ENA=0;MOTOR2_ENA=0;
	MOTOR3_ENA=0;MOTOR4_ENA=0;
}